FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc g++ librdkafka-dev libffi-dev python3-dev && \
    pip install poetry && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
